# Generated by Django 2.2.3 on 2019-07-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_todolist_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='head',
            field=models.CharField(max_length=50),
        ),
    ]
