# Generated by Django 2.2.3 on 2019-07-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20190704_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoApp',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('parent_id', models.IntegerField()),
            ],
        ),
    ]
